### PR TITLE
Bootstrap theme + show link names

### PR DESCRIPTION
**Pull request by ghost**
This bookmarklet is great!
Here's a proposal for:
* A bootstrap theme
* Show the links' names in the list
* Case-insensitive filters, applied on both URL and link names

Hope you like it!

### CODE REVIEW

**Comment by GammaC0de** [comment]
Very nice work but I must ask, is there any special reason that you removed the no-warp attributes?

**Comment by yannouchou** [comment]
It just felt nicer from my point of view... I also hoped it would be nicer on mobile, but so far I haven't been able to run it on FF mobile, not sure why.

**Comment by GammaC0de** [comment]
Please test https://github.com/pyload/pyload-bookmarklet/commit/051378736f16473ca2afa3864e7f6010e6c14043

**Comment by yannouchou** [comment]
Looks all good, thanks for considering it!

**Pull request merged**
